version: '3'
services:
  mcap2json:
    build: .
    image: mcap2json
    container_name: mcap2json
    hostname: mcap2json
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command: /bin/bash
